---
permalink: config-admin/3par-inserv-firmware-ssh-data-source.html 
sidebar: sidebar 
keywords:  
summary: 'O OnCommand Insight usa a fonte de dados do 3PAR InServ (firmware 2,2.2, SSH) para descobrir o inventário de matrizes de armazenamento HP 3PARPAR StoreServ.' 
---
= 3PAR fonte de dados do InServ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O OnCommand Insight usa a fonte de dados do 3PAR InServ (firmware 2,2.2, SSH) para descobrir o inventário de matrizes de armazenamento HP 3PARPAR StoreServ.



== Terminologia

A OnCommand Insight adquire as seguintes informações de inventário da fonte de dados do InServ 3PAR. Para cada tipo de ativo adquirido pelo Insight, a terminologia mais comum usada para esse ativo é mostrada. Ao visualizar ou solucionar problemas desta fonte de dados, tenha em mente a seguinte terminologia:

|===


| Termo do fornecedor/modelo | Termo de insight 


 a| 
Disco físico
 a| 
Disco



 a| 
Sistema de storage
 a| 
Armazenamento



 a| 
Nó do controlador
 a| 
Nó de storage



 a| 
Grupo de provisionamento comum
 a| 
Pool de storage



 a| 
Volume virtual
 a| 
Volume

|===
[NOTE]
====
Estes são apenas mapeamentos de terminologia comuns e podem não representar todos os casos para esta fonte de dados.

====


== Requisitos

* Endereço IP ou FQDN do cluster InServ
* Para inventário, nome de usuário somente leitura e senha para o servidor InServ.
* Para obter desempenho, leia-escreva o nome de utilizador e a palavra-passe para o servidor InServ.
* Requisitos de porta: 22 (coleta de inventário), 5988 ou 5989 (coleta de desempenho) [Nota: 3PAR o desempenho é suportado para o InServ os 3.x]
* Para a coleta de desempenho, confirme que o SMI-S está habilitado fazendo login no array 3PAR via SSH.




== Configuração

|===


| Campo | Descrição 


 a| 
IP do cluster
 a| 
Endereço IP ou nome de domínio totalmente qualificado do cluster InServ



 a| 
Nome de utilizador
 a| 
Nome de utilizador para o servidor InServ



 a| 
Palavra-passe
 a| 
Palavra-passe utilizada para o servidor InServ



 a| 
IP DO HOST SMI-S.
 a| 
Endereço IP do host do provedor SMI-S.



 a| 
Nome de utilizador SMI-S.
 a| 
Nome de utilizador para o anfitrião do fornecedor SMI-S.



 a| 
Palavra-passe SMI-S.
 a| 
Palavra-passe utilizada para o anfitrião do fornecedor SMI-S.

|===


== Configuração avançada

|===


| Campo | Descrição 


 a| 
Intervalo de enquete de inventário (min)
 a| 
Intervalo entre pesquisas de inventário (padrão de 40 minutos)



 a| 
Excluir dispositivos
 a| 
Lista separada por vírgulas de IPs de dispositivos a excluir



 a| 
Tempo limite de espera do processo SSH (seg.)
 a| 
Tempo limite do processo SSH (padrão de 60 segundos)



 a| 
Número de Resias SSH
 a| 
Número de tentativas de tentativa de SSH



 a| 
Tempo limite de espera da faixa SSH (seg.)
 a| 
Tempo limite de espera do banner SSH (padrão de 20 segundos)



 a| 
Porta SMI-S.
 a| 
Porta usada pelo SMI-S Provider Host



 a| 
Protocolo
 a| 
Protocolo utilizado para ligar ao fornecedor SMI-S.



 a| 
Namespace SMI-S.
 a| 
Namespace SMI-S.



 a| 
Intervalo de enquete de desempenho (seg)
 a| 
Intervalo entre sondagens de desempenho (padrão 300 segundos)



 a| 
Número de Resias de conexão SMI-S.
 a| 
Número de tentativas de tentativa de ligação SMI-S.

|===