---
permalink: config-admin/auditing-system-and-user-activities.html 
sidebar: sidebar 
keywords:  
summary: Se pretender localizar alterações inesperadas, pode visualizar uma trilha de auditoria do sistema OnCommand Insight e das atividades do utilizador. As mensagens de log de auditoria podem ser enviadas opcionalmente para syslog, além de serem exibidas na página Auditoria. 
---
= Sistema de auditoria e atividades do usuário
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se pretender localizar alterações inesperadas, pode visualizar uma trilha de auditoria do sistema OnCommand Insight e das atividades do utilizador. As mensagens de log de auditoria podem ser enviadas opcionalmente para syslog, além de serem exibidas na página Auditoria.



== Sobre esta tarefa

O Insight gera entradas de auditoria para qualquer atividade do usuário que afete a rede de armazenamento ou seu gerenciamento, incluindo o seguinte:

* Iniciar sessão
* Autorizando ou desautorizando um caminho
* Atualizando um caminho autorizado
* Definição de políticas ou limites globais
* Adicionar ou remover uma fonte de dados
* Iniciar ou parar uma fonte de dados
* Atualizando as propriedades da fonte de dados
* Adicionar, editar ou eliminar uma tarefa
* Removendo um grupo de aplicativos
* Identificar ou alterar a identificação de um dispositivo
* Crie um usuário
* Eliminar um utilizador
* Alteração da função do utilizador
* Modificar um usuário (convidado à Admin)
* Logout de um usuário (logout forçado ou logout manual)
* Eliminar uma unidade de aquisição
* Atualizar Licença
* A ativar a cópia de segurança
* A desativar a cópia de segurança
* Ativar ASUP (ativar proxy na mesma página é relatado no log de auditoria)
* Desativar ASUP (Desativar proxy na mesma página é relatado no log de auditoria)
* Segurança - volte a ligar, altere as palavras-passe do sistema.
* Remover/adicionar anotações em ativos
* Login/logoff do usuário do CAC
* Tempo limite da sessão do utilizador CAC




== Passos

. Abra o Insight em seu navegador.
. Clique em *Admin* e selecione *Audit*.
+
A página Auditoria exibe as entradas de auditoria em uma tabela.

. Você pode exibir os seguintes detalhes na tabela:
+
** *Hora*
+
Data e hora em que as alterações foram feitas

** *Usuário*
+
Nome do usuário associado à entrada de auditoria

** *Função*
+
Função da conta de usuário, que é convidado, usuário ou administrador

** *IP*
+
Endereço IP associado à entrada de auditoria

** *Ação*
+
Tipo de atividade na entrada de auditoria

** *Detalhes*
+
Detalhes da entrada de auditoria

+
Se houver uma atividade de usuário que afete um recurso, como uma fonte de dados ou um aplicativo, os detalhes incluem um link para a página de destino do recurso.

+
[NOTE]
====
Quando uma fonte de dados é excluída, os detalhes da atividade do usuário relacionados à fonte de dados não contêm mais um link para a página inicial da fonte de dados.

====


. Você pode exibir entradas de auditoria escolhendo um período de tempo específico (1 hora, 3 horas, 24 horas, 3 dias e 7 dias), com o Insight mostrando um número máximo de 1000 violações para o período de tempo selecionado.
+
Você pode clicar em um número de página abaixo da tabela para navegar pelos dados por página se houver mais dados do que se encaixa em uma única página.

. Você altera a ordem de classificação das colunas em uma tabela para ascendente (seta para cima) ou descendente (seta para baixo) clicando na seta no cabeçalho da coluna; para retornar à ordem de classificação padrão, clique em qualquer outro cabeçalho de coluna.
+
Por padrão, a tabela exibe as entradas em ordem decrescente.

. Você pode usar a caixa *filter* para mostrar apenas as entradas desejadas na tabela.
+
Para ver apenas as entradas de auditoria pelo usuário `izzyk`, digite `izzyk` a caixa *filter*.


