---
permalink: config-admin/brocade-efcm-9-5-to-9-7-data-sources.html 
sidebar: sidebar 
keywords:  
summary: 'A OnCommand Insight usa a fonte de dados do Brocade Enterprise Fabric Connectivity Manager (EFCM) para descobrir o inventário dos switches Brocade EFCM. O Insight suporta as versões 9,5, 9,6 e 9,7 do EFCM.' 
---
= Fonte de dados do Brocade Enterprise Fabric Connectivity Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A OnCommand Insight usa a fonte de dados do Brocade Enterprise Fabric Connectivity Manager (EFCM) para descobrir o inventário dos switches Brocade EFCM. O Insight suporta as versões 9,5, 9,6 e 9,7 do EFCM.



== Requisitos

[NOTE]
====
Este coletor de dados não está disponível a partir do OnCommand Insight 7,3.11.

====
* Endereço de rede ou nome de domínio totalmente qualificado para o servidor EFCM
* A versão EFCM deve ser 9,5, 9,6 ou 9,7
* Endereço IP do servidor EFCM
* Nome de utilizador e palavra-passe apenas de leitura para o servidor EFCM
* Acesso validado ao switch Connectrix pelo Telnet a partir do servidor Insight, usando o nome de usuário e senha somente leitura na porta 51512




== Configuração

|===


| *Campo* | *Descrição* 


 a| 
Servidor EFC
 a| 
Endereço IP ou nome de domínio totalmente qualificado do servidor EFC



 a| 
Nome de utilizador
 a| 
Nome de utilizador do comutador



 a| 
Palavra-passe
 a| 
Palavra-passe utilizada para o interrutor

|===


== Configuração avançada

|===


| *Campo* | *Descrição* 


 a| 
Intervalo de enquete de inventário (min)
 a| 
Intervalo entre pesquisas de inventário (padrão de 15 minutos)



 a| 
Nome da malha
 a| 
O nome da malha deve ser informado pela fonte de dados do EFCM. Deixe em branco para relatar o nome da tela como WWN.



 a| 
Porta de comunicação
 a| 
Porta utilizada para comunicação com o switch



 a| 
Ativar trapping
 a| 
Selecione para ativar a aquisição ao receber uma trap SNMP do dispositivo. Se você selecionar Ativar trapping, você também deve ativar o SNMP.



 a| 
Tempo mínimo entre armadilhas (seg)
 a| 
Tempo mínimo entre tentativas de aquisição acionadas por armadilhas (padrão de 15 segundos)



 a| 
Zonesets inativos
 a| 
Lista separada por vírgulas de Zonesets inativos nos quais realizar a aquisição, além de realizar a aquisição nos conjuntos de zonas ativas



 a| 
NIC a utilizar
 a| 
Especifique qual interface de rede deve ser usada na RAU ao gerar relatórios em dispositivos SAN



 a| 
Excluir dispositivos
 a| 
Lista separada por vírgulas de nomes de unidades a incluir ou excluir da sondagem



 a| 
Utilize a alcunha do interrutor EFCM como o nome do interrutor Insight
 a| 
Selecione para utilizar a alcunha do interrutor EFCM como o nome do interrutor Insight



 a| 
Intervalo de enquete de desempenho (seg)
 a| 
Intervalo entre sondagens de desempenho (padrão 300 segundos)

|===