---
permalink: config-admin/cdot-landing-page-terminology-storage-node.html 
sidebar: sidebar 
keywords:  
summary: Termos aplicáveis a objetos ou referências que você pode encontrar nas páginas iniciais de ativos de nó de armazenamento de dados do NetApp Clustered Data ONTAPs. 
---
= Nó de storage em cluster Data ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Termos aplicáveis a objetos ou referências que você pode encontrar nas páginas iniciais de ativos de nó de armazenamento de dados do NetApp Clustered Data ONTAPs.



== Terminologia do nó de storage do Clustered Data ONTAP

Os termos a seguir se aplicam a objetos ou referências que você pode encontrar nas páginas iniciais de ativos de pool de storage do NetApp Clustered Data ONTAP. Muitos desses termos também se aplicam a outros coletores de dados.

* Armazenamento -- de que storage array esse nó faz parte. Obrigatório.
* Parceiro HA -- nas plataformas onde um nó irá falhar para um e apenas um outro nó, ele geralmente será visto aqui.
* Estado -- integridade do nó. Disponível apenas quando o array estiver saudável o suficiente para ser inventariado por uma fonte de dados.
* Modelo -- nome do modelo do nó.
* Versão -- nome da versão do dispositivo.
* Número de série -- o número de série do nó.
* Memória -- memória base 2, se disponível.
* Utilização -- no ONTAP, este é um índice de tensão do controlador de um algoritmo proprietário. Em cada pesquisa de desempenho, um número entre 0 e 100% será relatado que é o maior da contenção de disco WAFL ou da utilização média da CPU. Se você observar valores sustentados > 50%, isso é indicativo de subdimensionamento -- potencialmente, um controlador/nó não é grande o suficiente ou não discos giratórios suficientes para absorver a carga de trabalho de gravação.
* IOPS -- derivado diretamente das chamadas ZAPI do ONTAP no objeto do nó.
* Latência -- derivado diretamente das chamadas ZAPI do ONTAP no objeto nó.
* Throughput -- derivado diretamente das chamadas ZAPI do ONTAP no objeto nó.
* Processadores -- contagem de CPU.

