---
permalink: config-admin/changing-user-passwords.html 
sidebar: sidebar 
keywords:  
summary: Um usuário com administrador Privileges pode alterar a senha de qualquer conta de usuário do OnCommand Insight definida no servidor local. 
---
= Alterando senhas de usuário
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um usuário com administrador Privileges pode alterar a senha de qualquer conta de usuário do OnCommand Insight definida no servidor local.



== Antes de começar

Os seguintes itens devem ter sido concluídos:

* Notificações para qualquer pessoa que faça login na conta de usuário que você está modificando.
* Nova palavra-passe a ser utilizada após esta alteração.




== Sobre esta tarefa

Ao utilizar este método, não é possível alterar a palavra-passe de um utilizador validado através do LDAP.



== Passos

. Inicie sessão com o administrador Privileges.
. Na barra de ferramentas Insight, clique em *Admin*.
. Clique em *Configuração*.
. Clique na guia *usuários*.
. Localize a linha que exibe a conta de usuário que você deseja modificar.
. À direita das informações do usuário, clique em *Editar conta de usuário*.
. Introduza a nova *Password* e, em seguida, introduza-a novamente no campo de verificação.
. Clique em *Salvar*.

