---
permalink: config-admin/changing-oncommand-insight-internal-user-passwords.html 
sidebar: sidebar 
keywords:  
summary: 'As políticas de segurança podem exigir que você altere as senhas em seu ambiente OnCommand Insight. Algumas das senhas em um servidor existem em um servidor diferente no ambiente, exigindo que você altere a senha em ambos os servidores. Por exemplo, quando você altera a senha do usuário "inventário" no Insight Server, você deve corresponder à senha do usuário "inventário" no conetor do servidor do Data Warehouse configurado para esse Insight Server.' 
---
= Alterando senhas internas de usuário do OnCommand Insight
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
As políticas de segurança podem exigir que você altere as senhas em seu ambiente OnCommand Insight. Algumas das senhas em um servidor existem em um servidor diferente no ambiente, exigindo que você altere a senha em ambos os servidores. Por exemplo, quando você altera a senha do usuário "'inventário'" no Insight Server, você deve corresponder à senha do usuário "'inventário'" no conetor do servidor do Data Warehouse configurado para esse Insight Server.



== Antes de começar

[NOTE]
====
Você deve entender as dependências das contas de usuário antes de alterar senhas. A falha na atualização de senhas em todos os servidores necessários resultará em falhas de comunicação entre os componentes do Insight.

====


== Sobre esta tarefa

A tabela a seguir lista as senhas de usuário internas do Insight Server e lista os componentes do Insight que têm senhas dependentes que precisam corresponder à nova senha.

|===


| Senhas do Insight Server | Alterações necessárias 


 a| 
_interno
 a| 



 a| 
aquisição
 a| 
LAU, RAU



 a| 
dwh_internal
 a| 
Armazém de dados



 a| 
hosts
 a| 



 a| 
inventário
 a| 
Armazém de dados



 a| 
raiz
 a| 

|===
A tabela a seguir lista as senhas de usuário internas do Data Warehouse e lista os componentes do Insight que têm senhas dependentes que precisam corresponder à nova senha.

|===


| Senhas do Data Warehouse | Alterações necessárias 


 a| 
cognos_admin
 a| 



 a| 
dwh
 a| 



 a| 
dwh_internal (alterado usando a IU de configuração do conetor do servidor)
 a| 
Servidor Insight



 a| 
dwhuser
 a| 



 a| 
hosts
 a| 



 a| 
Inventário (alterado usando a IU de configuração do conetor do servidor)
 a| 
Servidor Insight



 a| 
raiz
 a| 

|===
*Alterando senhas na IU de Configuração da conexão do servidor DWH*

A tabela a seguir lista a senha do usuário para a LAU e lista os componentes do Insight que têm senhas dependentes que precisam corresponder à nova senha.

|===


| Palavras-passe LAU | Alterações necessárias 


 a| 
aquisição
 a| 
Insight Server, RAU

|===