---
permalink: config-admin/controlling-data-source-polling.html 
sidebar: sidebar 
keywords:  
summary: Depois de fazer uma alteração em uma fonte de dados, você pode querer que ela pesquise imediatamente para verificar suas alterações, ou você pode querer adiar a coleta de dados em uma fonte de dados por um, três ou cinco dias enquanto você trabalha em um problema. 
---
= Controlar a polling da fonte de dados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depois de fazer uma alteração em uma fonte de dados, você pode querer que ela pesquise imediatamente para verificar suas alterações, ou você pode querer adiar a coleta de dados em uma fonte de dados por um, três ou cinco dias enquanto você trabalha em um problema.



== Passos

. Clique em *Admin* e navegue até a exibição da lista de fontes de dados
. Selecione a fonte de dados para a qual você deseja controlar a polling.
. Clique no link nome da fonte de dados.
. Na página de resumo da fonte de dados, verifique as informações e clique em uma dessas duas opções de polling:
+
** *Poll novamente* para forçar a fonte de dados a coletar dados imediatamente.
** *Adiar* e selecione a duração do atraso de votação de 3, 7 ou 30 dias.






== Depois de terminar

Se você adiou a coleta de dados em uma fonte de dados e deseja reiniciar a coleta, clique em *Resume* na página de resumo.
