---
permalink: config-admin/e-series-landing-page-terminology-storage.html 
sidebar: sidebar 
keywords:  
summary: Termos aplicáveis a objetos ou referências que podem ser encontradas nas páginas iniciais de ativos de storage do NetApp e-Series. 
---
= Storage e-Series
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Termos aplicáveis a objetos ou referências que podem ser encontradas nas páginas iniciais de ativos de storage do NetApp e-Series.



== Terminologia de storage do e-Series

Os termos a seguir se aplicam a objetos ou referências que você pode encontrar nas páginas iniciais de ativos de storage do NetApp e-Series. Muitos desses termos também se aplicam a outros coletores de dados.

* Modelo -- nome do modelo do dispositivo.
* Fornecedor -- mesmo nome do fornecedor que você veria se você estivesse configurando uma nova fonte de dados.
* Número de série -- o número de série da matriz. Em sistemas de storage de arquitetura de cluster, como o NetApp Clustered Data ONTAP, esse número de série pode ser menos útil do que os números de série individuais "'nós de storage".
* IP -- geralmente será o(s) IP(s) ou nome(s) de host conforme configurado na fonte de dados.
* Versão de microcódigo -- firmware.
* Capacidade bruta -- soma de base 2 de todos os discos físicos no sistema, independentemente de sua função.
* Latência -- uma representação do que o host enfrenta cargas de trabalho, tanto em leituras quanto em gravações. O Insight calcula uma média ponderada de IOPs derivada dos volumes no storage.
* Throughput -- o host total do array voltado para o throughput. O Insight resume a taxa de transferência dos volumes para obter esse valor.
* Gerenciamento -- isso pode conter um hiperlink para a interface de gerenciamento do dispositivo. Criado programaticamente pela fonte de dados do Insight como parte dos relatórios de inventário.

