---
permalink: config-admin/hp-eva-storage-sssu-data-source.html 
sidebar: sidebar 
keywords:  
summary: Para configuração, a fonte de dados do EVA Storage requer o endereço IP do servidor Command View e um nome de usuário e senha somente leitura para o software CV. O utilizador tem de ser definido no software CV. 
---
= Fonte de dados HP EVA Storage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para a configuração, a fonte de dados do EVA Storage (SSSU) requer o endereço IP do servidor da Command View (CV) e um nome de usuário e senha _somente leitura_ para o software CV. O utilizador tem de ser definido no software CV.



== Terminologia

A OnCommand Insight adquire as seguintes informações de inventário da fonte de dados HP EVA. Para cada tipo de ativo adquirido pelo Insight, a terminologia mais comum usada para esse ativo é mostrada. Ao visualizar ou solucionar problemas desta fonte de dados, tenha em mente a seguinte terminologia:

|===


| Termo do fornecedor/modelo | Termo de insight 


 a| 
Disco
 a| 
Disco



 a| 
Grupo de discos
 a| 
Grupo de discos (não modelado)



 a| 
Célula de armazenamento
 a| 
Armazenamento



 a| 
Disco virtual
 a| 
Pool de storage



 a| 
Disco virtual
 a| 
Volume

|===
[NOTE]
====
Estes são apenas mapeamentos de terminologia comuns e podem não representar todos os casos para esta fonte de dados.

====


== Requisitos de inventário

* Endereço IP do servidor CV
* Nome de utilizador apenas de leitura e palavra-passe para o software CV. O utilizador tem de ser definido no software CV.
* Software de terceiros instalado no servidor OnCommand Insight/RAU: `sssu.exe`. A `sssu.exe` versão deve corresponder à versão CV.
* Validação de acesso: Execute `sssu.exe` comandos usando nome de usuário e senha.




== Requisitos de desempenho

O pacote de software HP StorageWorks Command View EVA deve ser instalado no servidor OnCommand Insight. Alternativamente, você pode instalar uma Unidade de aquisição Remota (RAU) no servidor EVA:

. Instale o pacote de software HP StorageWorks Command View EVA no servidor OnCommand Insight ou instale uma unidade de aquisição remota no servidor EVA Command View.
. Localize o `evaperf.exe` comando. Por exemplo, `c:\Program Files\Hewlett-Packard\EVA Performance Monitor\`
. Usando o IP do servidor Command View, execute estas etapas:
+
.. Execute este comando onde 860 é a porta padrão `Evaperf.exe server <Command View Server IP\> 860 <username\>`
.. Digite a senha do servidor Command View no prompt de senha.
+
Isso deve retornar um prompt de linha de comando e nada mais.



. Verifique a configuração executando `evaperf.exe ls`o .
+
Você deve ver uma lista de arrays ou controladores gerenciados pelo servidor Command View. Cada linha mostra um controlador em uma matriz EVA.





== Configuração

|===


| *Campo* | *Descrição* 


 a| 
Servidor CommandView
 a| 
Endereço IP ou nome de domínio totalmente qualificado do EVA Storage Manager



 a| 
Nome de utilizador
 a| 
Nome de usuário para o gerenciador de Exibição de comando. O nome deve ser definido na Exibição de comando.



 a| 
Palavra-passe
 a| 
Palavra-passe utilizada para o gestor da Vista de comandos.



 a| 
Nome de utilizador de desempenho
 a| 
Para obter desempenho, o nome de usuário do gerenciador do Command View. O nome deve ser definido na Exibição de comando.



 a| 
Palavra-passe de desempenho
 a| 
Para obter desempenho, a senha usada para o gerenciador do Command View.

|===


== Configuração avançada

|===


| *Campo* | *Descrição* 


 a| 
Intervalo de enquete de inventário (min)
 a| 
Intervalo entre pesquisas de inventário (padrão de 40 minutos)



 a| 
CLI Home
 a| 
Caminho completo para o diretório inicial da CLI onde `sssu.exe` está localizado



 a| 
Inventário Excluir dispositivos
 a| 
Lista separada por vírgulas de nomes de dispositivos a incluir



 a| 
Intervalo de enquete de desempenho (seg)
 a| 
Intervalo entre sondagens de desempenho (padrão 300 segundos)



 a| 
CLI de desempenho Home
 a| 
Para o Array Performance, caminho completo para o diretório inicial da CLI onde o sssu.exe está localizado. Para validar o acesso, execute `sssu.exe`



 a| 
Tempo limite do comando (seg)
 a| 
`evaperf` tempo limite de espera de comando (padrão 600 segundos)



 a| 
O desempenho exclui dispositivos
 a| 
Lista separada por vírgulas de nomes de dispositivos a excluir da coleta de dados de desempenho

|===