---
permalink: config-admin/ibm-ds-cli-data-source.html 
sidebar: sidebar 
keywords:  
summary: 'A fonte de dados IBM DS (CLI) suporta apenas dispositivos DS6xxx e DS8xxx. Os dispositivos DS3xxx, DS4xxx e DS5xxx são suportados pela fonte de dados NetApp e-Series. Você deve consultar a matriz de suporte da fonte de dados Insight para modelos suportados e versões de firmware.' 
---
= Fonte de dados IBM DS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A fonte de dados IBM DS (CLI) suporta apenas dispositivos DS6xxx e DS8xxx. Os dispositivos DS3xxx, DS4xxx e DS5xxx são suportados pela fonte de dados NetApp e-Series. Você deve consultar a matriz de suporte da fonte de dados Insight para modelos suportados e versões de firmware.



== Terminologia

O OnCommand Insight adquire as seguintes informações de inventário da fonte de dados do IBM DS. Para cada tipo de ativo adquirido pelo Insight, a terminologia mais comum usada para esse ativo é mostrada. Ao visualizar ou solucionar problemas desta fonte de dados, tenha em mente a seguinte terminologia:

|===


| Termo do fornecedor/modelo | Termo de insight 


 a| 
Módulo de unidade de disco
 a| 
Disco



 a| 
Imagem de armazenamento
 a| 
Armazenamento



 a| 
Fundo de extensão
 a| 
Pool de storage



 a| 
Volume de bloco fixo
 a| 
Volume

|===
[NOTE]
====
Estes são apenas mapeamentos de terminologia comuns e podem não representar todos os casos para esta fonte de dados.

====


== Requisitos

* Endereço IP de cada DS array
* O nome de exibição de armazenamento é opcional e somente cosmético
* Nome de utilizador e palavra-passe apenas de leitura em cada DS array
* Software de terceiros instalado no servidor Insight: IBM dscli
* Validação de acesso: Execute `dscli` comandos usando o nome de usuário e senha
* Requisitos de porta: 80, 443 e 1750




== Configuração

|===


| Campo | Descrição 


 a| 
Armazenamento DS
 a| 
Endereço IP ou nome de domínio totalmente qualificado do DS Storage Host



 a| 
Nome de utilizador
 a| 
Nome utilizado para o DS CLI



 a| 
Palavra-passe
 a| 
Palavra-passe utilizada para a DS CLI



 a| 
Caminho executável dscli.exe
 a| 
Caminho completo para o ``dscli.exe``utilitário.

|===


== Configuração avançada

|===


| Campo | Descrição 


 a| 
Intervalo de enquete de inventário (min)
 a| 
Intervalo entre pesquisas de inventário (padrão de 40 minutos)



 a| 
Nome de exibição do armazenamento
 a| 
Nome do storage array do IBM DS



 a| 
Inventário Excluir dispositivos
 a| 
Lista separada por vírgulas de números de série do dispositivo a excluir da coleção de inventário



 a| 
Intervalo de enquete de desempenho (seg)
 a| 
Intervalo entre sondagens de desempenho (padrão 300 segundos)



 a| 
Tipo de filtro de desempenho
 a| 
Incluir: Dados coletados apenas de dispositivos na lista. Excluir: Nenhum dado desses dispositivos é coletado



 a| 
Lista de dispositivos de filtro de desempenho
 a| 
Lista separada por vírgulas de IDs de dispositivo para incluir ou excluir da coleção de desempenho

|===