---
permalink: config-admin/netapp-solidfire-data-source.html 
sidebar: sidebar 
keywords:  
summary: A fonte de dados NetApp SolidFire suporta configurações iSCSI e Fibre Channel SolidFire, tanto para inventário quanto para coleta de desempenho. 
---
= Fonte de dados NetApp SolidFire
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A fonte de dados NetApp SolidFire suporta configurações iSCSI e Fibre Channel SolidFire, tanto para inventário quanto para coleta de desempenho.

A fonte de dados do SolidFire utiliza a API REST do SolidFire. A unidade de aquisição em que reside a fonte de dados precisa ser capaz de iniciar conexões HTTPS com a porta TCP 443 no endereço IP de gerenciamento de cluster SolidFire. A fonte de dados precisa de credenciais capazes de fazer consultas de API REST no cluster SolidFire.



== Terminologia

A OnCommand Insight adquire as seguintes informações de inventário da fonte de dados NetApp SolidFire. Para cada tipo de ativo adquirido pelo Insight, a terminologia mais comum usada para esse ativo é mostrada. Ao visualizar ou solucionar problemas desta fonte de dados, tenha em mente a seguinte terminologia:

|===


| Termo do fornecedor/modelo | Termo de insight 


 a| 
Condução
 a| 
Disco



 a| 
Cluster
 a| 
Armazenamento



 a| 
Nó
 a| 
Nó de storage



 a| 
Volume
 a| 
Volume



 a| 
Porta Fibre Channel
 a| 
Porta



 a| 
Grupo Acesso volume, atribuição LUN
 a| 
Mapa de volume



 a| 
Sessão iSCSI
 a| 
Máscara de volume

|===
[NOTE]
====
Estes são apenas mapeamentos de terminologia comuns e podem não representar todos os casos para esta fonte de dados.

====


== Requisitos

A seguir estão os requisitos para configurar esta fonte de dados:

* Endereço IP virtual de gerenciamento
* Porta 443




== Configuração

|===


| Campo | Descrição 


 a| 
Endereço IP virtual de gerenciamento (MVIP)
 a| 
Endereço IP virtual de gerenciamento do cluster do SolidFire



 a| 
Nome de utilizador
 a| 
Nome utilizado para iniciar sessão no cluster SolidFire



 a| 
Palavra-passe
 a| 
Palavra-passe utilizada para iniciar sessão no cluster SolidFire

|===


== Configuração avançada

|===


| Campo | Descrição 


 a| 
Intervalo de enquete de inventário (min)
 a| 
Intervalo entre pesquisas de inventário (padrão de 60 minutos)



 a| 
Porta TCP
 a| 
Porta TCP usada para conetar ao servidor SolidFire (padrão 443 )



 a| 
Tempo limite da ligação (seg.)
 a| 
Tempo limite da ligação (predefinição 60 segundos)



 a| 
Intervalo de enquete de desempenho (seg)
 a| 
Intervalo entre sondagens de desempenho (padrão 300 segundos)

|===


== Solução de problemas

Quando o SolidFire relata um erro, ele é exibido no OnCommand Insight da seguinte forma:

`An error message was received from a SolidFire device while trying to retrieve data. The call was <method> (<parameterString> ). The error message from the device was (check the device manual): <message>`

Local:

* O <method> é um método HTTP, como GET ou PUT.
* O <parameterString> é uma lista separada por vírgulas de parâmetros que foram incluídos na CHAMADA REST.
* O <message> é o que o dispositivo retornou como a mensagem de erro.

