---
permalink: install-windows/remote-acquisition-unit-server-requirements.html 
sidebar: sidebar 
keywords: redhat 
summary: 'Tem de instalar uma unidade de aquisição remota (RAU) para adquirir informações de dispositivos SAN que estejam atrás de uma firewall, num local remoto, numa rede privada ou em diferentes segmentos de rede. Antes de instalar a RAU, você deve garantir que seu ambiente atenda aos requisitos do sistema operacional RAU, CPU, memória e espaço em disco.' 
---
= Requisitos do servidor da Unidade de aquisição Remota
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Tem de instalar uma unidade de aquisição remota (RAU) para adquirir informações de dispositivos SAN que estejam atrás de uma firewall, num local remoto, numa rede privada ou em diferentes segmentos de rede. Antes de instalar a RAU, você deve garantir que seu ambiente atenda aos requisitos do sistema operacional RAU, CPU, memória e espaço em disco.

|===


| Componente | Requisito 


 a| 
Sistema operacional
 a| 
Um computador executando o Microsoft Windows Server 2016, 2019 ou 2022 de 64 bits com o Service pack mais recente. É necessário instalar a versão 3,5 da estrutura Windows .NET antes de instalar o OnCommand Insight.



 a| 
CPU
 a| 
4 núcleos de CPU



 a| 
Memória
 a| 
16 GB DE RAM



 a| 
Espaço disponível em disco
 a| 
40 GB



 a| 
Rede
 a| 
Conexão Ethernet de 100 Mbps / 1 Gbps, endereço IP estático, conetividade IP a todos os dispositivos FC e uma porta necessária para o servidor OnCommand Insight (80 ou 443).



 a| 
Permissões
 a| 
Permissões de Administrador local no servidor RAU



 a| 
Verificação de vírus
 a| 
Durante a instalação deste componente do OnCommand Insight, você deve desativar completamente todos os scanners de vírus. Após a instalação, os caminhos usados pelo componente Insight devem ser excluídos da verificação de vírus. Além disso, você também deve excluir a pasta IBM/DB2 (por exemplo, _C: Arquivos de programas/IBM/DB2_) da verificação antivírus após a instalação.

|===