---
permalink: install-windows/uninstalling-insight.html 
sidebar: sidebar 
keywords:  
summary: Você pode desinstalar o servidor OnCommand Insight, se necessário. 
---
= Desinstalar o servidor OnCommand Insight
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode desinstalar o servidor OnCommand Insight, se necessário.

[NOTE]
====
*É altamente recomendável fazer backup do Vault* antes de desinstalar o OnCommand Insight.

Consulte link:../config-admin\/security-management.html["Ferramenta SecurityAdmin"]as instruções para obter mais informações.

====


== Antes de começar

Prática recomendada: Antes de desinstalar o Insight, faça backup do banco de dados do OnCommand Insight.



== Passos

. Faça login no servidor OnCommand Insight usando uma conta com o administrador Privileges.
. Certifique-se de que todas as janelas do Insight no servidor estão fechadas.
. Abra o recurso *Desinstalar um programa* no painel de controle e selecione o aplicativo OnCommand Insight para remoção.
. Clique em *Uninstall* e siga as instruções.

