---
permalink: install-linux/installation-prerequisites.html 
sidebar: sidebar 
keywords:  
summary: Antes de instalar o OnCommand Insight, você deve baixar a versão atual do software, adquirir a licença apropriada e configurar seu ambiente. 
---
= Pré-requisitos de instalação
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de instalar o OnCommand Insight, você deve baixar a versão atual do software, adquirir a licença apropriada e configurar seu ambiente.

Antes de instalar o OnCommand Insight, certifique-se de que tem o seguinte:

* Arquivos de software OnCommand Insight no pacote de instalação baixado para a versão atual
* Uma licença para operar a versão OnCommand Insight baixada
* O ambiente mínimo de hardware e software
+
O produto atual pode consumir recursos adicionais de hardware (devido à funcionalidade aprimorada do produto OnCommand Insight) que não foram consumidos com versões anteriores do produto OnCommand Insight.

* Um plano de implementação que inclui as configurações de hardware e rede para o servidor OnCommand Insight, o Armazém de dados e os relatórios e as unidades de aquisição remota.

