---
permalink: dwh/adding-a-reporting-user.html 
sidebar: sidebar 
keywords:  
summary: Você deve adicionar uma nova conta de usuário para cada pessoa que requer acesso ao portal de relatórios. Ter uma conta de usuário diferente para cada pessoa fornece uma maneira de controlar os direitos de acesso, preferências individuais e responsabilidade. 
---
= Adicionando um usuário de relatórios
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve adicionar uma nova conta de usuário para cada pessoa que requer acesso ao portal de relatórios. Ter uma conta de usuário diferente para cada pessoa fornece uma maneira de controlar os direitos de acesso, preferências individuais e responsabilidade.



== Antes de começar

Antes de adicionar um usuário do Reporting, você deve ter alocado um nome de usuário exclusivo, determinado a senha a ser usada e verificado a função ou funções corretas do usuário. Essas funções são especializadas no portal de relatórios.



== Passos

. Faça login como administrador no Portal do Armazém de dados em `+https://hostname/dwh+`, onde `hostname` está o nome do sistema em que o Armazém de dados OnCommand Insight está instalado.
. No painel de navegação à esquerda, clique em *User Management*.
. Na janela *User Management*, clique em *Add New User* (Adicionar novo usuário).
. Insira as seguintes informações para o novo usuário do Reporting:
+
** *Nome de utilizador*
+
Nome de utilizador (alfanumérico, incluindo a-z, A-Z e 0-9) para a conta

** *Endereço de e-mail*
+
Endereço de e-mail associado à conta de usuário e necessário se o usuário assinar qualquer relatório

** *Senha*
+
Senha para fazer login no OnCommand Insight com essa conta de usuário, que geralmente é selecionada pelo usuário e confirmada na interface

** *Insight role*
+
Funções disponíveis para o usuário com permissões apropriadas

+
[NOTE]
====
As opções para a função OnCommand Insight são mostradas somente se o OnCommand Insight estiver instalado na mesma máquina que as instalações de relatórios, o que não é típico.

====
** *Funções de relatório*
+
Função de relatório para esta conta de utilizador (por exemplo, Pro Author)

+
[NOTE]
====
A função Administrador é única. Você pode adicionar essa função a qualquer usuário.

====


. Clique em *Add*.

