---
permalink: dwh/editing-the-site-name-and-viewing-system-information.html 
sidebar: sidebar 
keywords:  
summary: Você pode visualizar informações de atualização do sistema, módulo, licença e Data Warehouse. 
---
= Visualização de informações do sistema
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode visualizar informações de atualização do sistema, módulo, licença e Data Warehouse.



== Passos

. Faça login no Portal do Armazém de dados em `+https://hostname/dwh+`, onde `hostname` está o nome do sistema onde o Armazém de dados OnCommand Insight está instalado.
. No painel de navegação à esquerda, clique em *informações do sistema*.
. Na guia *sistema*, revise as informações do sistema e edite-as o nome do site, se necessário, fazendo o seguinte:
+
.. Clique em *Editar Nome do Site*
.. Digite o novo nome do site e clique em *Salvar*.


. Para ver as informações do aplicativo (nome do aplicativo, módulo, versão e data de instalação), clique na guia *informações do aplicativo*.
. Para ver as informações da licença (protocolo, código, data de validade e quantidade), clique no separador *licenças*.
. Para ver as informações de atualização do aplicativo (nome do aplicativo, data, data, hora, usuário e tamanho do arquivo), clique em *Histórico de atualização*.

