---
permalink: dwh/restoring-the-data-warehouse-database.html 
sidebar: sidebar 
keywords:  
summary: Você pode restaurar um banco de dados do Data Warehouse usando o arquivo .zip criado quando você fez backup desse banco de dados do Data Warehouse. 
---
= Restaurar a base de dados do Data Warehouse
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode restaurar um banco de dados do Data Warehouse usando o `.zip` arquivo que foi criado quando você fez backup desse banco de dados do Data Warehouse.



== Sobre esta tarefa

Ao restaurar um banco de dados do Data Warehouse, você também tem a opção de restaurar as informações da conta de usuário do backup. As tabelas de gerenciamento de usuários são usadas pelo mecanismo de relatório do Data Warehouse em uma instalação somente do Data Warehouse.



== Passos

. Faça login no Portal do Armazém de dados em `+https://hostname/dwh+`, onde `hostname` está o nome do sistema no qual o Armazém de dados OnCommand Insight está instalado.
. No painel de navegação à esquerda, clique em *Backup/Restore*.
. Na seção *Restaurar banco de dados e relatórios*, clique em *Procurar* e localize o `.zip` arquivo que contém o backup do Data Warehouse.
. Se pretender restaurar relatórios ou dados de conta de utilizador, selecione uma ou ambas as seguintes caixas de verificação:
+
** *Restaurar banco de dados*
+
Inclui configurações do Data Warehouse, data marts, conexões e informações de conta de usuário.

** *Restaurar relatórios*
+
Inclui relatórios personalizados, relatórios pré-criados, alterações feitas em relatórios pré-projetados e configurações de relatórios que você criou no Portal de relatórios.

+
[NOTE]
====
Se o backup do banco de dados contiver um relatório personalizado que tenha uma barra (/) ou um colchete aberto ([) em seu nome (por exemplo, US IT Center Switch Port Boston/July), a operação de restauração renomeará o relatório, substituindo a barra ou o colchete aberto por um sublinhado (por exemplo, US IT Center Switch Port Boston_July).

====


. Clique em *Restaurar*.
+
Após o processo de restauração ser concluído, uma mensagem é exibida abaixo do botão Restaurar. Se o processo de restauração for bem-sucedido, a mensagem indica sucesso. Se o processo de restauração falhar, a mensagem informará a exceção específica que causou a falha. Se ocorrer uma exceção e o processo de restauração falhar, o banco de dados original será redefinido automaticamente.


