---
permalink: dwh/viewing-storage-arrays-consolidation-issues.html 
sidebar: sidebar 
keywords:  
summary: Os dados reportados para matrizes de armazenamento são derivados do data mart do Inventário. Para todos os storages de armazenamento, há uma linha para cada conetor que relata sobre eles, bem como o conetor primário a partir do qual cada array é tomado. 
---
= Exibindo problemas de consolidação de matrizes de armazenamento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os dados reportados para matrizes de armazenamento são derivados do data mart do Inventário. Para todos os storages de armazenamento, há uma linha para cada conetor que relata sobre eles, bem como o conetor primário a partir do qual cada array é tomado.



== Passos

. Faça login no Portal do Armazém de dados em `+https://hostname/dwh+`, onde `hostname` está o nome do sistema onde o Armazém de dados OnCommand Insight está instalado.
. No painel de navegação à esquerda, clique em *solução de problemas*.
. Na seção *consolidação do chassi*, clique em *matrizes de armazenamento SAN*.
. Opcionalmente, para filtrar dados nessa exibição, digite uma parte do texto na caixa filtro e clique em *filtro*. Para limpar o filtro, exclua o texto na caixa filtro e clique em *filtro*. Você pode filtrar por nome de storage, IP de storage, modelo de fornecedor ou ID de objeto OnCommand Insight.
+
O filtro é sensível a maiúsculas e minúsculas.

. Reveja os seguintes dados:
+
** *GUID*
+
Identificador exclusivo global para este tipo de dispositivo consolidado (storage array)

** *Nome*
+
Nome da matriz de armazenamento consolidada como aparece no Data Warehouse

** *IP*
+
Endereço IP da matriz de armazenamento consolidada

** *Fornecedor e modelo*
+
Nome do fornecedor que vende a matriz de armazenamento consolidada e o número do modelo do fabricante

** *Conetor principal*
+
Nome do conetor OnCommand Insight que era a fonte real dos dados

** *Conetores disponíveis*
+
Todos os conetores OnCommand Insight em que reside o storage array consolidado

** *Insight ID*
+
ID do storage array consolidado no chassi do OnCommand Insight onde reside o conetor principal

** *Insight Change time*
+
Quando uma atualização ocorreu no OnCommand Insight para o storage array e quando o mesmo storage array foi atualizado em outros servidores OnCommand Insight




